### ISSUE TITLE
error in modulated_deformable_im2col_cuda: invalid device function

### ISSUE THREAD

**Issue by ZhWL123456** [CharlesShang/DCNv2#35]
I compile it success, but when I use this api, I encounter the problem.
Do anyone can figure it?
I use pytorch1.3  cuda10.0 RTX2080Ti ubuntu18.06

**Comment by austinmw** [comment]
I'm having the same issue. Python 3.6.10, pytorch 1.4.0, cuda 10.0. 4x V100. Amazon Linux 2 AMI.

**Comment by RyanXingQL** [comment]
The same issue.

**Comment by ZhWL123456** [comment]
I changed the pytorch version to avoid the problem.

**Comment by yinhai86924** [comment]
> I changed the pytorch version to avoid the problem.
which  pytorch version you used?  what is the Cuda and Cudnn version? thank you

**Comment by yinhai86924** [comment]
> I'm having the same issue. Python 3.6.10, pytorch 1.4.0, cuda 10.0. 4x V100. Amazon Linux 2 AMI.

have you solved this problem? can you offer some advice?

**Comment by Booomshaker** [comment]
> I changed the pytorch version to avoid the problem.

Could you tell me which pytorch version you choosed?pip install or conda install?

**Comment by jozhang97** [comment]
I fixed by switching to 1.1
`conda install pytorch==1.1.0 torchvision==0.3.0 cudatoolkit=10.0 -c pytorch`

**Comment by ZhWL123456** [comment]
> I fixed by switching to 1.1
> `conda install pytorch==1.1.0 torchvision==0.3.0 cudatoolkit=10.0 -c pytorch`

Thank u~
